/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { SeedNoEnvironmentClient } from "../src/Client";

const client = new SeedNoEnvironmentClient({
    token: process.env.ENV_TOKEN || "token",
    environment: process.env.TESTS_BASE_URL || "test",
});

describe("Dummy", () => {
    test("constructor", () => {
        expect(client.dummy).toBeDefined();
    });
});
