/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { SeedCustomAuthClient } from "../src/Client";

const client = new SeedCustomAuthClient({
    token: process.env.ENV_TOKEN || "token",
    environment: process.env.TESTS_BASE_URL || "test",
});

describe("CustomAuth", () => {
    test("constructor", () => {
        expect(client.customAuth).toBeDefined();
    });
});
