/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { FiddleClient } from "../src/Client";

const client = new FiddleClient({
    token: process.env.ENV_TOKEN || "token",
    environment: process.env.TESTS_BASE_URL || "test",
});

describe("NoReqBody", () => {
    test("constructor", () => {
        expect(client.noReqBody).toBeDefined();
    });
});
