/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { SeedPackageYmlClient } from "../src/Client";

const client = new SeedPackageYmlClient({
    token: process.env.ENV_TOKEN || "token",
    environment: process.env.TESTS_BASE_URL || "test",
});

describe("SeedPackageYmlClient", () => {
    test("echo", async () => {
        const response = await client.echo("Hello world!");
        expect(response).toEqual("Hello world!");
    });
});
