/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { SeedPackageYmlClient } from "../src/Client";

const client = new SeedPackageYmlClient({
    token: process.env.ENV_TOKEN || "token",
    environment: process.env.TESTS_BASE_URL || "test",
});

describe("Service", () => {
    test("nop", async () => {
        const response = await client.service.nop("id-219xca8");
        expect(response).toEqual(undefined);
    });
});
