/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { SeedBasicAuthClient } from "../src/Client";

const client = new SeedBasicAuthClient({
    token: process.env.ENV_TOKEN || "token",
    environment: process.env.TESTS_BASE_URL || "test",
});

describe("BasicAuth", () => {
    test("constructor", () => {
        expect(client.basicAuth).toBeDefined();
    });
});
