/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { SeedApiWideBasePathClient } from "../src/Client";

const client = new SeedApiWideBasePathClient({
    token: process.env.ENV_TOKEN || "token",
    environment: process.env.TESTS_BASE_URL || "test",
});

describe("Service", () => {
    test("constructor", () => {
        expect(client.service).toBeDefined();
    });
});
