/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { SeedExamplesClient } from "../src/Client";

const client = new SeedExamplesClient({
    token: process.env.ENV_TOKEN,
    environment: process.env.TESTS_BASE_URL || "test",
});

describe("SeedExamplesClient", () => {
    test("echo", async () => {
        const response = await client.echo("Hello world!\\n\\nwith\\n\\tnewlines");
        expect(response).toEqual("Hello world!\\n\\nwith\\n\\tnewlines");
    });
});
