/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { SeedTraceClient } from "../src/Client";

const client = new SeedTraceClient({
    token: process.env.ENV_TOKEN || "token",
    environment: process.env.TESTS_BASE_URL || "test",
});

describe("Sysprop", () => {
    test("constructor", () => {
        expect(client.sysprop).toBeDefined();
    });
});
