/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { SeedExhaustiveClient } from "../src/Client";

const client = new SeedExhaustiveClient({
    token: process.env.ENV_TOKEN || "token",
    environment: process.env.TESTS_BASE_URL || "test",
});

describe("InlinedRequests", () => {
    test("constructor", () => {
        expect(client.inlinedRequests).toBeDefined();
    });
});
