/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { SeedNurseryApiClient } from "../src/Client";

const client = new SeedNurseryApiClient({
    token: process.env.ENV_TOKEN || "token",
    environment: process.env.TESTS_BASE_URL || "test",
});

describe("Package", () => {
    test("constructor", () => {
        expect(client.package).toBeDefined();
    });
});
