/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { SeedUndiscriminatedUnionsClient } from "../src/Client";

const client = new SeedUndiscriminatedUnionsClient({
    token: process.env.ENV_TOKEN || "token",
    environment: process.env.TESTS_BASE_URL || "test",
});

describe("Union", () => {
    test("constructor", () => {
        expect(client.union).toBeDefined();
    });
});
