/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { SeedErrorPropertyClient } from "../src/Client";

const client = new SeedErrorPropertyClient({
    token: process.env.ENV_TOKEN || "token",
    environment: process.env.TESTS_BASE_URL || "test",
});

describe("PropertyBasedError", () => {
    test("constructor", () => {
        expect(client.propertyBasedError).toBeDefined();
    });
});
