/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { SeedQueryParametersClient } from "../src/Client";

const client = new SeedQueryParametersClient({
    token: process.env.ENV_TOKEN || "token",
    environment: process.env.TESTS_BASE_URL || "test",
});

describe("User", () => {
    test("constructor", () => {
        expect(client.user).toBeDefined();
    });
});
