/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { SeedMultiUrlEnvironmentClient } from "../src/Client";

const client = new SeedMultiUrlEnvironmentClient({
    token: process.env.ENV_TOKEN || "token",
    environment: {
        production: process.env.TESTS_BASE_URL || "test",
        staging: process.env.TESTS_BASE_URL || "test",
    },
});

describe("Ec2", () => {
    test("constructor", () => {
        expect(client.ec2).toBeDefined();
    });
});
