/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { SeedMultiUrlEnvironmentClient } from "../src/Client";

const client = new SeedMultiUrlEnvironmentClient({
    token: process.env.ENV_TOKEN,
    environment: process.env.TESTS_BASE_URL || "test",
});

describe("Ec2", () => {
    test("constructor", () => {
        expect(client.ec2).toBeDefined();
    });
});
