/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { SeedLiteralClient } from "../src/Client";

const client = new SeedLiteralClient({
    token: process.env.ENV_TOKEN || "token",
    environment: process.env.TESTS_BASE_URL || "test",
});

describe("Path", () => {
    test("send", async () => {
        const response = await client.path.send("123");
        expect(response).toEqual({ message: "The weather is sunny", status: 200, success: true });
    });
});
