/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { SeedObjectsWithImportsClient } from "../src/Client";

const client = new SeedObjectsWithImportsClient({
    token: process.env.ENV_TOKEN || "token",
    environment: process.env.TESTS_BASE_URL || "test",
});

describe("Optional", () => {
    test("constructor", () => {
        expect(client.optional).toBeDefined();
    });
});
