/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { SeedAuthEnvironmentVariablesClient } from "../src/Client";

const client = new SeedAuthEnvironmentVariablesClient({
    environment: process.env.TESTS_BASE_URL || "test",
    token: process.env.TESTS_AUTH || "test",
});

describe("Service", () => {
    test("constructor", () => {
        expect(client.service).toBeDefined();
    });
});
